---

- name: Creating glance database
  mysql_db: name=glance state=present login_user=root login_password={{ MARIADB_PASS }}

- name: Creating glance DB user
  mysql_user: name=glance password={{ GLANCE_DBPASS }} priv='glance.*:ALL' state=present login_user=root login_password={{ MARIADB_PASS }} host="{{ item }}"
  with_items:
    - "localhost.localdomain"
    - "127.0.0.1"
    - "::1"
    - "compute1"
    - "10.0.0.31"
    - "controller1"
    - "10.0.0.11"

- name: Creating glance user
  os_user: 
    cloud: default
    state: present
    name: glance
    password: "{{ GLANCE_PASS }}"
    email: demo@test.domain
    domain: default

- name: adding admin role to glance
  os_user_role:
    cloud: default
    state: present
    user: glance
    role: admin
    project: service

- name: Creating glance service
  os_keystone_service:
    cloud: default
    state: present
    name: glance
    service_type: image
    description: OpenStack Image Service

- name: Creating Image service API endpoints
  shell: |
    export OS_USERNAME=admin
    export OS_PASSWORD={{ ADMIN_PASS }}
    export OS_PROJECT_NAME=admin
    export OS_USER_DOMAIN_NAME=Default
    export OS_PROJECT_DOMAIN_NAME=Default
    export OS_AUTH_URL=http://controller1:35357/v3
    export OS_IDENTITY_API_VERSION=3
    openstack endpoint list | grep glance
    if [ $? -eq 1 ]; then
      openstack endpoint create --region RegionOne image public http://controller1:9292
      openstack endpoint create --region RegionOne image internal http://controller1:9292
      openstack endpoint create --region RegionOne image admin http://controller1:9292
    fi

- name: Installing openstack glance packages
  yum: name={{ item }} state=installed
  with_items:
    - openstack-glance

- name: Transferring glance-api config
  template: src=glance-api.conf.j2 dest=/etc/glance/glance-api.conf

- name: Transferring glance-registry.conf
  template: src=glance-registry.conf.j2 dest=/etc/glance/glance-registry.conf

- name: populating identity service database
  become: yes
  become_user: glance
  command: glance-manage db_sync
  ignore_errors: yes

- name: Starting glance api
  service: name=openstack-glance-api state=restarted enabled=yes

- name: Starting glance registry
  service: name=openstack-glance-registry state=restarted enabled=yes

- name: Copying cirros
  copy: src=cirros-0.3.5-x86_64-disk.img dest=/tmp/cirros-0.3.5-x86_64-disk.img

- name: Installing cirros image
  os_image:
    cloud: default
    name: cirros
    container_format: bare
    disk_format: qcow2
    state: present
    filename: /tmp/cirros-0.3.5-x86_64-disk.img
    kernel: cirros-vmlinuz
    ramdisk: cirros-initrd
    properties:
      cpu_arch: x86_64
      distro: ubuntu
