---
- name: Disabling firewalld
  service: name=firewalld state=stopped enabled=no

- name: Disabling NetworkManager
  service: name=NetworkManager state=stopped enabled=no

- name: Enabling basic network
  service: name=network state=started enabled=yes

- name: Updating /etc/hosts
  copy: src=etc.hosts dest=/etc/hosts

- name: Installing chrony
  yum: name=chrony state=present

- name: Transferring Chrony configure
  copy: src=etc.chrony-compute dest=/etc/chrony.conf

- name: Starting chrony server
  service: name=chronyd state=started enabled=yes
