---

- name: Installing horizon packages
  yum: name=openstack-dashboard state=installed

- name: Transfering horizon local_settings
  template: src=local_settings.j2 dest=/etc/openstack-dashboard/local_settings

- name: Restarting httpd and memcached
  service: name={{ item }} state=restarted
  with_items:
    - httpd
    - memcached
